### ISSUE TITLE
[NOTICE] 각자 작업한 문서 컨펌

### ISSUE THREAD

**Issue by kimtaegyuu** [20-1-SKKU-OSS/2020-1-OSS-8#18]
김태규(@kimtaegyuu)->김유현(@Idontknowrithm )
김유현(@Idontknowrithm )->박정은(@jepark132)
박정은(@jepark132)->이동준(@ldj9876)
이동준(@ldj9876)->김태규(@kimtaegyuu)

6/8(월) 까지 상대방이 번역한 문서에 오류가 있는지 확인해주세요.

**Comment by ldj9876** [comment]
baby_rnn.md
paper : 종이 -> 논문
tokenize, parse_stories, get_stories 주석 미번역 부분 번역
(아마 #으로 된 부분만 번역하시고 ''' ''' 으로 감싸진 부분은 안하신듯)

**Comment by ldj9876** [comment]
baby_memnn
reference : 증빙 서류 -> 참고 문헌
line 8 번역체 수정 및 epoch -> 에포크
''' ''' 로 감싸진 주석 미번역 -> 번역
encoder : 엔코더 -> 인코더
