### ISSUE TITLE
[번역수정요청] 이동준 -> 김태규

### ISSUE THREAD

**Issue by ldj9876** [20-1-SKKU-OSS/2020-1-OSS-8#28]
문법 오류:
 - paper : 종이 -> 논문  baby_rnn
 - reference : 증빙 서류 -> 참고 문헌 baby_memnn
 - epoch -> 에포크로 변경 번역 readme.md에 나와있음  거의모든문서
 - encoder : 엔코더 -> 인코더 baby_memnn
 - Original paper accuracy : 원 문서 -> 원본 논문
 - accuracy -> 정확도 미번역 (readme.md에 나와있습니다.)  cifar-10_resnet
 - 그라디언트 상승 -> 경사상승법 (readme.md에 있음) convolution_filter_visualization
 - 그림 -> 이미지 convolution_filter_visualization 

번역 미완성:
 - ''' ''' 이나 """ """ 으로 감싸진 주석 번역이 전부 되어있지 않음 baby_rnn 제외한 모든문서
 - CIFAR-10 CNN line 92 93 94 97 98 99 110 미번역
 - cifar-10_resnet line 73 95 216 229 241 279 미번역

번역 스타일:
 - convolution_filter_visualization 121 122 번역체 수정
 - convolution_filter_visualization 149 ~ 152 번역체 수정.

**Comment by ldj9876** [comment]
컨펌 내용 pull requests 했습니다.

**Comment by kimtaegyuu** [comment]
완료했습니다.
