### ISSUE TITLE
[번역수정요청] deep_dream.md

### ISSUE THREAD

**Issue by jepark132** [20-1-SKKU-OSS/2020-1-OSS-8#29]
#### 제목 영어로 번역 부탁드립니다

문법 오류:
 - line 99 :  손실에 대한 dream wrt의 그래디언트를 계산
 - line156 : hyperparameter : 매개변수 -> 하이퍼 매개변수

번역 미완성:
 - line 141 : process : 과정

번역 스타일:
 - line 81 : 가져옵니다 -> 가져오기, 우리는 고유한 이름을 지정했었습니다 -> 고유한 이름으로 지정했었음
 - line 87 : 추가합니다 -> 추가
 - line 92 : 방지한다 -> 방지

**Comment by ldj9876** [comment]
수정완료했습니다.
