### ISSUE TITLE
[번역수정요청] image_ocr.md

### ISSUE THREAD

**Issue by jepark132** [20-1-SKKU-OSS/2020-1-OSS-8#30]
#### 제목 번역 부탁드립니다.

문법 오류:
 - line 186 : generator 는 생성->제너레이터로 표현합니다 (readme참고)
 - line 267 : 일반적인 규칙과는 다릅니다 -> 전형적인 케라스 관례와 다름
 - line 353 : 케 -> 케라스
 - line 485 : -> RNN에 들어갈 입력 크기를 줄임
 - line 489 : -> LSTM 만큼은 아니지만 GRU도 잘 작동함

번역 미완성:
 - line 28 : then install python dependencies 가 빠짐.

번역 스타일:
 - line 70 : 생성합니다-> 생성
 - line 83-84 : 83에 또한 임의의 글꼴 및 회전, 84에 스펙클 노이즈를 사용합니다.
 - line 112 : 학습시킵니다 -> 학습시킴
 - line 186 : 사용합니다 -> 사용함
 - line 188 : 생성됩니다 -> 생성됨
 - line 228 : 정렬됩니다 -> 정렬됨
 - line 237 : 포함합니다 -> 포함함
 - line 264 : 수행됩니다 -> 수행됨
 - line 354  : 이루어집니다 -> 이루어짐
 - line 359 : 중요합니다 -> 중요함
 - line 364 : 검색이여야 합니다 -> 검색이여야 함
 - line 365 : 충분합니다 -> 충분함
 - line 501 : 변환합니다 -> 변환함
 - line 512 : 구현됩니다 -> 구현됨
 - line 517 : 같습니다 -> 높이는 것으로 보임

**Comment by ldj9876** [comment]
수정완료했습니다.
