### ISSUE TITLE
[번역수정요청] mnist_acgan.md

### ISSUE THREAD

**Issue by jepark132** [20-1-SKKU-OSS/2020-1-OSS-8#31]
#### 제목도 영어로 번역해주세요
 
문법 오류:
 - line 49 : L 글자가 빠진것 같습니다
 - line 92 : 을 만드십시오 -> 생성
 - line 146 : 판별자 -> 제너레이터(readme 참고)
 - line 186-193 : 코드 위치가 잘못됨, 번역체도 수정바랍니다
 - line 199 : line 202 문장와 위치 바뀜
 - line 210 : (batch_size, 1) -> (len(image_batch), 1)이 되야함
 - line 217 : -> 한방향의 soft real/fake 레이블 사용
 - line 233-234 : 233에 우리의 목적은 생성자에 대해 fake, not-fake레이블에 대해 not-fake라고 하도록, 234에 제너레이터가 판별자를 속이도록 훈련하는 것

번역 미완성:
 - 시작 부분 : 기존 문서의  # -*- coding: utf-8 -*- 부분이 빠졌습니다.

번역 스타일:
 - line 50 : 레이블 입니다 -> 레이블
 - line 73 : 공간입니다 -> 공간
 - line 76 : 될 것입니다 -> 될 것임
 - line 120 : 입니다 삭제
 - line 152 : 가져옵니다 -> 가져오기
 - line 155 : 우리는 -> 삭제, 원한다 -> 원함
 - line 167 : 만듭니다 -> 만듦
 - line 228 : 만든다 -> 만듦,
 - line 229 : 최적화 하도록 합니다 -> 최적화시킴
 - line 313 : 가져온다 -> 가져옴

**Comment by ldj9876** [comment]
line 146 : 판별자 -> 제너레이터(readme 참고)
이부분은 generator 을 판별자로 번역을 한 것이 아닌 
GAN에서 discriminator을 번역한 것이므로 이 번역이 맞는것 같습니다.

**Comment by ldj9876** [comment]
수정완료했습니다.
