### ISSUE TITLE
[번역수정요청] conv_lstm.md

### ISSUE THREAD

**Issue by jepark132** [20-1-SKKU-OSS/2020-1-OSS-8#32]
문법 오류:
 - line 41 : -> 내부에 3-7개의 움직이는 윈도우를 포함한 움직이는movie를 생성 
 - line 42 : -> 윈도우는 1x1 또는 2x2 픽셀 형태로 
 - line 43 : -> 시간이 지남에 따라 선형으로 이동함
 - line 104 : 영화 -> 윈도우

번역 미완성:

번역 스타일:
 - line 14 : 만듭니다 -> 만듦
 - line 75 : 줄입니다 -> 줄임
 - line 78 : 한다는 것입니다 ->함
 - line 106 : 예측합니다 -> 예측함
 - line 117 : 비교하십시오 -> 비교

**Comment by ldj9876** [comment]
수정했습니다.
