### ISSUE TITLE
[번역수정요청] imdb_fasttext.md

### ISSUE THREAD

**Issue by Idontknowrithm** [20-1-SKKU-OSS/2020-1-OSS-8#34]
번역 미완성:
 - 첫 번째 표에서
    -> Embedding : 임베딩
    -> Accuracy, 5 epochs : 정확도, 5에폭
    -> Speed (s/epoch) : 속도(초/에폭)
    -> Hardware : 하드웨어

 - 효율적인 embedding 층부터 시작 : 효율적인 임베딩 층부터 시작
 - embeddings를 평균 낼  GlobalAveragePooling1D를 더하라 : 임베딩을 평균 낼 
   GlobalAveragePooling1D를 추가

번역 스타일:
 - 단일 단위 출력 레이어에 반영하여 S자형으로 압착한다 : 단일 단위 출력 레이어에 반영하여 S자형 
    으로 압착

**Comment by jepark132** [comment]
수정 반영했습니다
