### ISSUE TITLE
[번역수정요청] lstm_seq2seq.md

### ISSUE THREAD

**Issue by Idontknowrithm** [20-1-SKKU-OSS/2020-1-OSS-8#36]
번역 미완성:
 - 훈련할 eqochs의 수 : 훈련할 에폭의 수
 - Here's the drill : 훈련 방식

기타:
 - 데이터 다운로드 부분 지워주시기 바랍니다(url 없어서 필요없을 것 같음)

**Comment by jepark132** [comment]
수정 반영했습니다
