### ISSUE TITLE
[번역수정요청] cnn_seq2seq.md

### ISSUE THREAD

**Issue by Idontknowrithm** [20-1-SKKU-OSS/2020-1-OSS-8#37]
문법 오류:
 - 시퀀스 : 순서형

번역 미완성:
 - 훈련할 epochs의 수 : 훈련할 에폭의 수

기타:
 - 파일 이름 lstm_seq2seq_restore.md 로 바꿔주시기 바랍니다.

**Comment by jepark132** [comment]
수정 반영했습니다
