### ISSUE TITLE
[번역수정요청] lstm-stateful.md

### ISSUE THREAD

**Issue by kimtaegyuu** [20-1-SKKU-OSS/2020-1-OSS-8#38]
번역 미완성:
 - 링크 걸려 있는 문장 해석 부탁드립니다(ex. 원문 첫 번째 줄) 
 

번역 스타일:
 - ~합니다 에서 ~함 과 같은 형식으로 변경해주세요

**Comment by Idontknowrithm** [comment]
링크 걸려있는 문장에서 그 링크 url을 따라가보니 문서가 손실되어있어 굳이 해석할 필요가 없다고 판단하여 내용을 삭제했습니다. 번역 스타일에 대해서는 수정을 완료하였습니다.
